### ISSUE TITLE
[FireFox] Mouseover Response element menu makes the block jump

### ISSUE THREAD

**Issue by epicformbuilder** [dubovds/epic#10]
**FireFox Only!**

<img width="1028" alt="Forms_page" src="https://user-images.githubusercontent.com/10811565/79049990-b3cbb380-7c2f-11ea-9dea-932872c701d0.png">

**Comment by dubovds** [comment]
fixed

**Comment by message-dimke** [comment]
fixed, doesn't jump anymore
