### ISSUE TITLE
[Safari,Chrome,FireFox] Top navigation menu, the one which is underlined red, is different across 3 major browsers

### ISSUE THREAD

**Issue by epicformbuilder** [dubovds/epic#11]
**Safari** 
Has 1 pixel line under the 'red line'

<img width="157" alt="Forms_page" src="https://user-images.githubusercontent.com/10811565/79050077-43716200-7c30-11ea-84db-3526fd36ed33.png">

**Chrome**
Ideal. No one pixel line under the 'red line'

<img width="156" alt="Editor" src="https://user-images.githubusercontent.com/10811565/79050093-5edc6d00-7c30-11ea-9f38-156ece35fbcf.png">

**FireFox**
'Red line' is one pixel below the menu

<img width="154" alt="Editor" src="https://user-images.githubusercontent.com/10811565/79050109-79aee180-7c30-11ea-81f6-9d398ec15bc5.png">

This behaviour is true for all the pages where top menu is: index, responses, editor, ... 
All of them.

**Comment by dubovds** [comment]
fixed

**Comment by epicformbuilder** [comment]
Fix confirmed
