### ISSUE TITLE
Hovered forms and responses element must have form name highlighted and clickable

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#16]
Hey, this one is a link which is also red when element is hovered

<img width="769" alt="03_1_form_rsp_list_jpg" src="https://user-images.githubusercontent.com/9010963/79101965-6b68de80-7d72-11ea-906b-d504ca71f314.png">

**Comment by dubovds** [comment]
done

**Comment by message-dimke** [comment]
Fix confirmed. Done
