### ISSUE TITLE
Actions frame doesn't match the design

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#18]
This is what we have:
![Actions](https://user-images.githubusercontent.com/9010963/79381086-198aa900-7f6a-11ea-873b-acdd2865a59d.png)

This is how it is on the design:
![06_01_action_settings_dark_side_jpg](https://user-images.githubusercontent.com/9010963/79381150-30310000-7f6a-11ea-9fab-121bde55869f.png)

**Comment by dubovds** [comment]
fixed

**Comment by message-dimke** [comment]
Fix confirmed, done
