### ISSUE TITLE
Action frame doesn't match the design 

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#19]
The design:
![06_01_action_settings_dark_side_jpg](https://user-images.githubusercontent.com/9010963/79381286-6a9a9d00-7f6a-11ea-99a6-a16e1d9816c6.png)

Our layout:
![Actions](https://user-images.githubusercontent.com/9010963/79381376-8dc54c80-7f6a-11ea-9808-bf5a029e55f1.png)

**Comment by dubovds** [comment]
сделал так, что при ховере, серая линия исчезает.
посмотри, скажи свое мнение.

**Comment by message-dimke** [comment]
fix confirmed, done
