### ISSUE TITLE
Разное расстояние

### ISSUE THREAD

**Issue by dubovds** [dubovds/epic#2]
![0-02-05-dbc380002666b4af01930c4e1eee388be4475f52d00e64b3637993c0c44cce94_1c6d9bb2035049](https://user-images.githubusercontent.com/16684226/79005081-c88c4680-7b5e-11ea-9c32-c38016de598c.jpg)

**Comment by dubovds** [comment]
Исправил.

**Comment by epicformbuilder** [comment]
Fix confirmed

**Comment by message-dimke** [comment]
Done
