### ISSUE TITLE
Actions list has different top and bottom spacing

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#20]
![Actions](https://user-images.githubusercontent.com/9010963/79381584-dc72e680-7f6a-11ea-9ea7-6e52e1ca32b9.png)

This is the design:
![06_01_action_settings_dark_side_jpg](https://user-images.githubusercontent.com/9010963/79381651-f9a7b500-7f6a-11ea-8f89-5bbb99507fb8.png)

**Comment by dubovds** [comment]
fixed

**Comment by message-dimke** [comment]
ok, lets leave like it is now
