### ISSUE TITLE
Switch has border on the design

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#21]
Our layout:
![Actions](https://user-images.githubusercontent.com/9010963/79381729-1ba13780-7f6b-11ea-96ee-71cdd8734cff.png)

The design:
![06_01_action_settings_dark_side_jpg](https://user-images.githubusercontent.com/9010963/79381844-41c6d780-7f6b-11ea-9212-b8ec93c8c48e.png)

**Comment by dubovds** [comment]
![image](https://user-images.githubusercontent.com/16684226/79471415-46db6380-800b-11ea-9d6d-04d617e6d238.png)

проверил пипеткой в фотошопе - нет там бордера. Макет 06.01

**Comment by message-dimke** [comment]
Ok, close the ticket
