### ISSUE TITLE
Forms list element border is missing (when hovered)

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#22]
The design:
<img width="435" alt="03_1_form_rsp_list_jpg" src="https://user-images.githubusercontent.com/9010963/79382406-1f818980-7f6c-11ea-940d-845bb07fbb7a.png">

**Comment by dubovds** [comment]
надо обсудить. На макете этот бордер выходит на 2 пикселя вправо и влево. если реализовать такое поведение блока при наведении, то контент будет скакать

**Comment by message-dimke** [comment]
хорошо, когда контент скачет это фигово, отменяем бордер в этом случае.
