### ISSUE TITLE
[Safari] Fix the transition for icons

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#23]
![Forms_page](https://user-images.githubusercontent.com/9010963/79384773-2ca07780-7f70-11ea-8f88-03120465d110.png)

**Comment by message-dimke** [comment]
![Forms_page](https://user-images.githubusercontent.com/9010963/79384961-7ab57b00-7f70-11ea-9007-938709c90593.png)

**Comment by dubovds** [comment]
fixed svg icons for first and second items

**Comment by message-dimke** [comment]
fix confirmed
