### ISSUE TITLE
Make Response item in a list highlight with a border as form item does on the forms list

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#27]
This is how we have forms list items highlighted:
![Document](https://user-images.githubusercontent.com/9010963/80149962-32c1d400-85c0-11ea-9fe9-28dbcaaf6cbf.png)

Can we have Dashboard Response items highlight the same with a border, not with shadow?

**Comment by dubovds** [comment]
done

**Comment by message-dimke** [comment]
done
