### ISSUE TITLE
Response item with and without image have different sizes

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#28]
Once you do add class .show to the image, the size changes

![Document](https://user-images.githubusercontent.com/9010963/80229428-158d1400-8659-11ea-8411-a5f7850b8dcd.png)

**Comment by dubovds** [comment]
fixed. 
Added class .tab__item_image. 
Class .show should add to. tab__item_image now

![image](https://user-images.githubusercontent.com/16684226/80247464-c0f89180-8676-11ea-9aa8-1ac4222aaa24.png)

**Comment by message-dimke** [comment]
fix confirmed
