### ISSUE TITLE
Точки залазят

### ISSUE THREAD

**Issue by dubovds** [dubovds/epic#3]
![0-02-05-c3881bc2c1c7394d19108d03e1031dc83ab2c2d09fc33109c4a1ce6682fbc6c4_1c6d9bb20350ca](https://user-images.githubusercontent.com/16684226/79005145-f07baa00-7b5e-11ea-8489-751c9f851718.jpg)

**Comment by dubovds** [comment]
fixed

**Comment by epicformbuilder** [comment]
Fix confirmed

**Comment by message-dimke** [comment]
Done
