### ISSUE TITLE
Implement Month|Week|Today stats

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#32]
![Screenshot_16_05_2020__17_22](https://user-images.githubusercontent.com/9010963/82129643-f8b5ad80-97cc-11ea-9c84-bc953cd21398.png)

**Comment by dubovds** [comment]
inserted this block on index page.

**Comment by message-dimke** [comment]
are those blocks compatible? 
I mean block from index page, can it be reused on the form page as well?

**Comment by dubovds** [comment]
Yes, it is
