### ISSUE TITLE
Move popup out of builder to make if available on all pages

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#33]
This one

![Screenshot_16_05_2020__23_30](https://user-images.githubusercontent.com/9010963/82129715-56e29080-97cd-11ea-85e1-1a6afb1ed0a3.png)

**Comment by dubovds** [comment]
добавил попап в index.html
строка 525-607

скрипт к нему находится на строках 668 - 677 и 710-711

название переменных можно поменять :)
