### ISSUE TITLE
Extra space with Component panel is open

### ISSUE THREAD

**Issue by message-dimke** [dubovds/epic#36]
Some extra blank space appears when opening a Component panel

![Editor_and_DevTools_-_localhost_3000_editor_4625e1f1-0698-4bea-ac1f-6a2e2d3d88e2_fields_from__dashboard_forms-and-responses](https://user-images.githubusercontent.com/9010963/83339120-481ed200-a2d3-11ea-9b1d-d50bb6bef378.png)

**Comment by dubovds** [comment]
fixed.
hid the components panel at large screen
