### ISSUE TITLE
Рамка при ховере в  action

### ISSUE THREAD

**Issue by dubovds** [dubovds/epic#4]
![0-02-05-90807e88d68996d874e8ff6306fc4bafb4babe21fb4b0dff2104692fa2200ba2_1c6d9bb2035115](https://user-images.githubusercontent.com/16684226/79014110-de0b6b80-7b72-11ea-9958-cda70df2982f.jpg)

**Comment by dubovds** [comment]
Надо разобраться с этими рамками. Нужен совместный просмотр макета

**Comment by message-dimke** [comment]
Вот пример активной рамки на Action

<img width="579" alt="06_01_action_settings_dark_side_jpg" src="https://user-images.githubusercontent.com/9010963/79102106-bda9ff80-7d72-11ea-9775-ca08c0e0bac5.png">

**Comment by message-dimke** [comment]
Вот, я нашел еще один пример как дизайнер прорисовал похожий элемент. Я думаю надо выбрать или это или рамку серую/красную. Что-то одно. 

<img width="575" alt="08_2_shipping_flat_rate_light_jpg" src="https://user-images.githubusercontent.com/9010963/79102295-1ed1d300-7d73-11ea-91c0-d5d98160211d.png">

Какой вариант тебе больше нравится. Как здесь или с рамкой?

**Comment by dubovds** [comment]
сделал с красной рамкой
