### ISSUE TITLE
Settings panel, margins are all wrong

### ISSUE THREAD

**Issue by epicformbuilder** [dubovds/epic#41]
![Editor](https://user-images.githubusercontent.com/10811565/83978548-fd273f00-a910-11ea-96d6-23eb9ca6e77b.png)

Here is the original design 
![04 03_settings_dark side](https://user-images.githubusercontent.com/10811565/83978556-09ab9780-a911-11ea-8677-df6fcef4925e.jpg)

**Comment by dubovds** [comment]
подогнать отступы прям как по дизайну не получится - у нас разные шрифты. Максимально их приблизил к макету. Использовал наложение макета на верстку.
