### ISSUE TITLE
не большое расстояние от низа

### ISSUE THREAD

**Issue by dubovds** [dubovds/epic#5]
![0-02-05-2fb19234fae5083ecbe743a20d9eb8fb457e78b969af141e8656fcc5a1dda76a_1c6d9bb203535a](https://user-images.githubusercontent.com/16684226/79014296-44908980-7b73-11ea-8e29-69ae32332243.jpg)

**Comment by dubovds** [comment]
fixed

**Comment by epicformbuilder** [comment]
Fixed in all browsers

**Comment by message-dimke** [comment]
Done
