### ISSUE TITLE
Сверстать попоап, открывающийся при клике на How to use Data Tags?

### ISSUE THREAD

**Issue by dubovds** [dubovds/epic#6]
Находится в папке 07_help-text

![0-02-05-8071019cf17b33241c15800d018f295cdb43fa71ab22c4fc9d12252e546ad3eb_1c6d9bb2035a4e](https://user-images.githubusercontent.com/16684226/79014670-11022f00-7b74-11ea-94ca-7e5d51567aae.jpg)

**Comment by dubovds** [comment]
я его создал. Он получается сильно длинным. Когда прокручиваешь его, то задний контент должен стоять на месте или как сейчас?

**Comment by dubovds** [comment]
done
Вопрос, при скроллинге попапа, задний контент пусть тоже скроллится и остается или его фиксировать?

**Comment by message-dimke** [comment]
а фиксировать сложно? если нет то фиксировать

**Comment by dubovds** [comment]
Please check it

**Comment by message-dimke** [comment]
Checked. Done.
