### ISSUE TITLE
Animation duration/timeframe/period is different for combined elements (icon + text) on mouse over

### ISSUE THREAD

**Issue by epicformbuilder** [dubovds/epic#7]
**Safari only!**

Here is an image with highlighted elements, which are subject of incorrect behaviour.

<img width="1192" alt="responses" src="https://user-images.githubusercontent.com/10811565/79049508-c1336e80-7c2c-11ea-9a1f-872cf88083ef.png">

When you mouseover those elements, icon and text have different transition time 
from inactive to active states. 

Can this one be changed?

**Comment by dubovds** [comment]
Safari isn't support transition svg

**Comment by epicformbuilder** [comment]
Can it be done that for Safari only text will have no transition as well, so the icon and text active/inactive transition would be the same? For Chrome and FireFox leave as it is now.

**Comment by dubovds** [comment]
please check menu icons animation on page form.html

**Comment by message-dimke** [comment]
Works as a charm for Safari. For FireFox icons became dark w/o animation, I added a new ticket for that

**Comment by message-dimke** [comment]
Closing this one as there is another ticket on the subject
