### ISSUE TITLE
[FilreFox] Icon and Text are not horizontally aligned

### ISSUE THREAD

**Issue by epicformbuilder** [dubovds/epic#8]
**FileFox Only!**

When Safari and Chrome are all the same, FireFox is different and alignment is broken.

<img width="1197" alt="responses" src="https://user-images.githubusercontent.com/10811565/79049806-5daa4080-7c2e-11ea-9e42-6644ea721438.png">

**Comment by dubovds** [comment]
fixed

**Comment by epicformbuilder** [comment]
Fix confirmed
