### ISSUE TITLE
[FireFox] Actions Tab Icon went crazy

### ISSUE THREAD

**Issue by epicformbuilder** [dubovds/epic#9]
**FireFox only!**

<img width="729" alt="Editor" src="https://user-images.githubusercontent.com/10811565/79049912-1d978d80-7c2f-11ea-8614-e29530ef4e60.png">

**Comment by epicformbuilder** [comment]
Sorry, all the icons went crazy

<img width="729" alt="Editor" src="https://user-images.githubusercontent.com/10811565/79049929-3ef87980-7c2f-11ea-82fa-b38fed45492e.png">

**Comment by dubovds** [comment]
fixed

**Comment by epicformbuilder** [comment]
Fix confirmed
